###
POST http://127.0.0.1:8000/api/v1/register/
Content-Type: application/json

{
  "email": "kiwi@mail.ru",
  "first_name": "Kiwi",
  "last_name": "Newrise",
  "password": "4myfreddy"
}

###
POST http://127.0.0.1:8000/api/v1/token/
Content-Type: application/json

{
    "email": "kiwi@mail.ru",
    "password": "4myfreddy"
}

###
GET http://127.0.0.1:8000/api/v1/users/me/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk1ODE3NjcyLCJpYXQiOjE2OTUyMTI4NzIsImp0aSI6ImY5M2ZiOWJkMjNhYTQ1ZTNiNDg4M2NlNjMwZTIxMDdkIiwidXNlcl9pZCI6Mn0.-oaJ1S2sDta2OPGryvlfD8TQYoGV7mbdIJScpwgYJUY

###
GET http://127.0.0.1:8000/api/v1/orders/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk1ODAzOTg3LCJpYXQiOjE2OTUxOTkxODcsImp0aSI6IjBiNmM2MmI5YTAxZjRiYTU5NjRhODZhYjg2OTJiYmYzIiwidXNlcl9pZCI6Mn0.AFPljwRHdP_EuWIRDO4Z3xXk6Dcdk7YFzWeywzBUr_U

###
POST http://127.0.0.1:8000/api/v1/orders/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk1NzMwOTY1LCJpYXQiOjE2OTUxMjYxNjUsImp0aSI6IjdjYzcwZmQ0YzhkMTQwZjNiYWUwZDc5MjQ4ZGYwN2UwIiwidXNlcl9pZCI6MX0.i947lFR5svWQo6St_OiPlFY06SWX6w5xTlTz3IU3S6A

{
  "comment": "Хочу доставку после 18:00",
  "contact_phone_number": "+79354987523",
  "delivery_address": "603005, г. Нижний Новгород, пл. Минина и Пожарского, д.5 (вход в арке)"
}

###
GET http://127.0.0.1:8000/api/v1/orders/6/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk1NzMwOTY1LCJpYXQiOjE2OTUxMjYxNjUsImp0aSI6IjdjYzcwZmQ0YzhkMTQwZjNiYWUwZDc5MjQ4ZGYwN2UwIiwidXNlcl9pZCI6MX0.i947lFR5svWQo6St_OiPlFY06SWX6w5xTlTz3IU3S6A

###
PATCH http://127.0.0.1:8000/api/v1/orders/6/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk1NzMwOTY1LCJpYXQiOjE2OTUxMjYxNjUsImp0aSI6IjdjYzcwZmQ0YzhkMTQwZjNiYWUwZDc5MjQ4ZGYwN2UwIiwidXNlcl9pZCI6MX0.i947lFR5svWQo6St_OiPlFY06SWX6w5xTlTz3IU3S6A

{
  "status": "Собирается",
  "article_number": "5"
  # "comment": "Хочу доставку после 10:00",
  # "contact_phone_number": "",
  # "delivery_address": "Ленивка, д.2"
  # "products": [
  #   {
  #     "id": 0,
  #     "amount": 12,
  #     "price_per_unit": 1200
  #   }
  # ]
}
