# Generated by Django 4.1.5 on 2023-10-26 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={
                "ordering": ["product"],
                "verbose_name": "корзина",
                "verbose_name_plural": "корзины",
            },
        ),
    ]
