# Generated by Django 4.1.5 on 2023-09-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='None', help_text='Введите логин', max_length=150, verbose_name='логин'),
        ),
    ]
