# Generated by Django 4.1.5 on 2023-09-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                help_text="Введите имя", max_length=150, verbose_name="имя пользователя"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                help_text="Введите фамилию",
                max_length=150,
                verbose_name="фамилия пользователя",
            ),
        ),
    ]
