# Generated by Django 4.1.5 on 2023-09-17 09:20

from django.db import migrations

import users.managers


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.managers.MyUserManager()),
            ],
        ),
    ]
