# Generated by Django 4.1.5 on 2023-09-17 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_alter_category_description_alter_category_name_and_more"),
        ("users", "0006_shoppingcart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcart",
            name="product",
            field=models.ForeignKey(
                help_text="Выберите товар",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="user",
            field=models.ForeignKey(
                help_text="Выберите пользователя",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
