# Generated by Django 4.1.5 on 2023-09-18 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_alter_product_category"),
        ("users", "0007_alter_shoppingcart_product_alter_shoppingcart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcart",
            name="product",
            field=models.ForeignKey(
                help_text="Выберите товар",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_product",
                to="products.product",
                verbose_name="Товар",
            ),
        ),
    ]
