# Generated by Django 4.1.5 on 2023-09-16 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="название")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="описание"),
                ),
                (
                    "discount",
                    models.PositiveSmallIntegerField(
                        help_text="Введите целое число от 1 до 100",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Скидка должна быть больше нуля"
                            ),
                            django.core.validators.MaxValueValidator(
                                100,
                                "Скидка не должна превышать                              100 %.",
                            ),
                        ],
                        verbose_name="cкидка",
                    ),
                ),
                ("date_start", models.DateField(verbose_name="Дата начала акции")),
                ("date_end", models.DateField(verbose_name="Дата окончания акции")),
                ("slug", models.SlugField(unique=True, verbose_name="уникальный слаг")),
            ],
            options={
                "verbose_name": "акция",
                "verbose_name_plural": "акции",
                "ordering": ("name",),
            },
        ),
    ]
