# Generated by Django 4.1.5 on 2023-09-17 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(max_length=255, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="event",
            name="discount",
            field=models.PositiveSmallIntegerField(
                help_text="Введите целое число от 1 до 100",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Скидка должна быть больше нуля"
                    ),
                    django.core.validators.MaxValueValidator(
                        100,
                        "Скидка не должна превышать                                  100 %.",
                    ),
                ],
                verbose_name="cкидка",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Слаг"),
        ),
    ]
