# Generated by Django 4.1.5 on 2023-09-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_event_description_alter_event_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(
                help_text="Введите описание", max_length=255, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(
                help_text="Введите название", max_length=30, verbose_name="Название"
            ),
        ),
    ]
