# Generated by Django 4.1.5 on 2023-09-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_alter_event_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(
                help_text="Загрузите картинку акции",
                null=True,
                upload_to="events/",
                verbose_name="картинка акции",
            ),
        ),
    ]
