# Generated by Django 4.1.5 on 2023-09-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_event_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите картинку акции",
                null=True,
                upload_to="events/",
                verbose_name="картинка акции",
            ),
        ),
    ]
