# Generated by Django 4.1.5 on 2023-09-22 13:39

from django.db import migrations, models
import events.validators


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0009_alter_event_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date_end",
            field=models.DateField(
                validators=[events.validators.validate_dates],
                verbose_name="Дата окончания акции",
            ),
        ),
    ]
