# Generated by Django 4.1.5 on 2023-09-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_alter_event_date_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date_end",
            field=models.DateField(verbose_name="Дата окончания акции"),
        ),
    ]
