###
GET http://127.0.0.1:8000/orders
Content-Type: application/json

###
POST http://127.0.0.1:8000/orders
Content-Type: application/json

{
  "customer": 1,
  "product": 2,
  "amount": 3
}
