###
POST http://127.0.0.1:8000/api/v1/register/
Content-Type: application/json

{
  "email": "kiwi@mail.ru",
  "first_name": "Kiwi",
  "last_name": "Newrise",
  "password": "4myfreddy"
}

###
POST http://127.0.0.1:8000/api/v1/token/
Content-Type: application/json

{
    "email": "kiwi@mail.ru",
    "password": "4myfreddy"
}

###
GET http://127.0.0.1:8000/api/v1/users/me/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk3MzA4OTEzLCJpYXQiOjE2OTY3MDQxMTMsImp0aSI6ImU4NWJlOTUzNTFjNDRmMzA4NDM1ODBjMjkwMWExNWVjIiwidXNlcl9pZCI6Mn0.eikWDeldPQGdiYdzTfFXO4H5E-iTJ8QW9CtHyyNXCKw
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk3MzAyMzg2LCJpYXQiOjE2OTY2OTc1ODYsImp0aSI6ImQ2MjcxN2RjYzQwYzQ5Nzc4MDEzYmQ1ZDUyNmE4MWUzIiwidXNlcl9pZCI6MX0.u6j_ee-BgXK_jnFhYhaimXG7fptIjmsN5_oBaHbOJR0


###
GET http://127.0.0.1:8000/api/v1/products/1/shopping_cart/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk3MzA4OTEzLCJpYXQiOjE2OTY3MDQxMTMsImp0aSI6ImU4NWJlOTUzNTFjNDRmMzA4NDM1ODBjMjkwMWExNWVjIiwidXNlcl9pZCI6Mn0.eikWDeldPQGdiYdzTfFXO4H5E-iTJ8QW9CtHyyNXCKw
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk3MzAyMzg2LCJpYXQiOjE2OTY2OTc1ODYsImp0aSI6ImQ2MjcxN2RjYzQwYzQ5Nzc4MDEzYmQ1ZDUyNmE4MWUzIiwidXNlcl9pZCI6MX0.u6j_ee-BgXK_jnFhYhaimXG7fptIjmsN5_oBaHbOJR0
