###
GET http://127.0.0.1:8000/api/v1/orders/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk3NjI0Mjk3LCJpYXQiOjE2OTcwMTk0OTcsImp0aSI6IjRhOGJhOTEwZDM1YTRkZGRiZGMxNzIyNWE5Yjg3Njc0IiwidXNlcl9pZCI6Mn0.tKSQMSRAOeUXriNAzzwfPQF4Vl5V0shPO-cc3fgqCN0
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk3NjI0MjYwLCJpYXQiOjE2OTcwMTk0NjAsImp0aSI6ImM4NTRlYzAwZWRhYzQzZDdhNmNmYjA3NDY0MGY2NDFkIiwidXNlcl9pZCI6MX0.q5ZjP7f3mssMDh7n3f9gosRAjvf7V4fkmpBkdyUJgyk

###
POST http://127.0.0.1:8000/api/v1/orders/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk3NjI0Mjk3LCJpYXQiOjE2OTcwMTk0OTcsImp0aSI6IjRhOGJhOTEwZDM1YTRkZGRiZGMxNzIyNWE5Yjg3Njc0IiwidXNlcl9pZCI6Mn0.tKSQMSRAOeUXriNAzzwfPQF4Vl5V0shPO-cc3fgqCN0
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk3NjI0MjYwLCJpYXQiOjE2OTcwMTk0NjAsImp0aSI6ImM4NTRlYzAwZWRhYzQzZDdhNmNmYjA3NDY0MGY2NDFkIiwidXNlcl9pZCI6MX0.q5ZjP7f3mssMDh7n3f9gosRAjvf7V4fkmpBkdyUJgyk

{
  "comment": "Хочу доставку 5:00",
  "contact_phone_number": "+79031234568",
  "address": "МСК"
}
