# Generated by Django 4.1.5 on 2023-09-18 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliveryaddress",
            options={
                "ordering": ("owner",),
                "verbose_name": "адрес доставки",
                "verbose_name_plural": "адреса доставки",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "default_related_name": "orders",
                "ordering": ("customer",),
                "verbose_name": "заказ",
                "verbose_name_plural": "заказы",
            },
        ),
        migrations.AlterModelOptions(
            name="orderproduct",
            options={
                "ordering": ("order_id",),
                "verbose_name": "продукт в составе заказа",
                "verbose_name_plural": "продукты в заказе",
            },
        ),
        migrations.RemoveField(
            model_name="order",
            name="article_number",
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                through="orders.OrderProduct", to="products.product"
            ),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="apartment",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RU", "Россия"),
                    ("BY", "Белоруссия"),
                    ("KZ", "Казахстан"),
                    ("UZ", "Узбекистан"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveryAddresses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="price_total",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="purchase_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="orderproduct",
            constraint=models.UniqueConstraint(
                fields=("order_id", "product_id", "purchase_price"),
                name="unique_product_in_order",
            ),
        ),
    ]
