# Generated by Django 4.1.5 on 2023-09-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderproduct",
            options={
                "ordering": ("product_id",),
                "verbose_name": "продукт в составе заказа",
                "verbose_name_plural": "продукты в заказе",
            },
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="item_total",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Стоимость позиции"
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="purchase_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена за единицу товара",
            ),
        ),
    ]
