# Generated by Django 4.1.5 on 2023-09-17 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_options_alter_order_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderproduct",
            options={
                "verbose_name": "заказ продукта",
                "verbose_name_plural": "заказы продукции",
            },
        ),
    ]
