# Generated by Django 4.1.5 on 2023-09-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_orderproduct_options_orderproduct_item_total_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="purchase_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена за единицу",
            ),
        ),
    ]
