# Generated by Django 4.1.5 on 2023-09-22 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_orderproduct_purchase_price"),
        ("orders", "0003_order_contact_phone_number_and_more"),
    ]

    operations = []
