# Generated by Django 4.1.5 on 2023-09-24 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_merge_20230921_2030"),
        ("orders", "0004_merge_20230922_1608"),
    ]

    operations = []
