# Generated by Django 4.1.5 on 2023-09-17 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_alter_category_description_alter_category_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0004_alter_order_address_alter_order_comment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderproduct",
            options={
                "verbose_name": "продукт в заказе",
                "verbose_name_plural": "продукты в заказе",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="article_number",
            field=models.CharField(max_length=50, verbose_name="Артикул"),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                help_text="Укажите заказчика",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Заказчик",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="amount",
            field=models.IntegerField(
                default=0, help_text="Введите количество", verbose_name="Количество"
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="order_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orderProducts",
                to="orders.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="product_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="purchase_price",
            field=models.FloatField(verbose_name="Цена за единицу товара в заказе"),
        ),
    ]
