# Generated by Django 4.1.5 on 2023-09-26 06:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_merge_20230924_1222"),
        ("orders", "0005_merge_20230924_1834"),
    ]

    operations = []
