# Generated by Django 4.1.5 on 2023-10-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_merge_20230926_0938"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(
                help_text="Введите адрес доставки",
                max_length=255,
                null=True,
                verbose_name="Адрес доставки",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="article_number",
            field=models.CharField(max_length=50, null=True, verbose_name="Артикул"),
        ),
    ]
