# Generated by Django 4.1.5 on 2023-09-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="description",
            field=models.TextField(max_length=255, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(max_length=255, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(max_length=255, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Название"),
        ),
    ]
