# Generated by Django 4.1.5 on 2023-09-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_brand_description_alter_brand_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(null=True, unique=True, verbose_name="Слаг"),
        ),
    ]
