# Generated by Django 4.1.5 on 2023-10-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_long_name_product_structure_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="long_name",
            field=models.CharField(
                help_text="Введите наименование",
                max_length=255,
                verbose_name="Наименование товара длинное",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Введите наименование",
                max_length=50,
                verbose_name="Наименование товара короткое",
            ),
        ),
    ]
