# Generated by Django 4.1.5 on 2023-10-24 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_long_name_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                help_text="Введите производителя",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brand",
                to="products.brand",
                verbose_name="Брэнд",
            ),
        ),
    ]
