# Generated by Django 4.1.5 on 2023-09-17 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(default=1, unique=True, verbose_name="Слаг"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(max_length=100, verbose_name="Брэнд"),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.PositiveSmallIntegerField(
                help_text="Введите целое число от 1 до 100",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Скидка должна быть больше нуля"
                    ),
                    django.core.validators.MaxValueValidator(
                        100,
                        "Скидка не должна превышать                                  100 %.",
                    ),
                ],
                verbose_name="cкидка",
            ),
        ),
        migrations.DeleteModel(
            name="Brand",
        ),
    ]
