# Generated by Django 4.1.5 on 2023-09-17 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_event_description_alter_event_discount_and_more"),
        ("products", "0004_alter_category_slug_alter_product_brand_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["id"],
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["id"],
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={
                "ordering": ["id"],
                "verbose_name": "корзина",
                "verbose_name_plural": "корзины",
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="rating",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.event",
                verbose_name="Акция",
            ),
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="amount",
            field=models.IntegerField(default=0, verbose_name="Количество"),
        ),
        migrations.DeleteModel(
            name="Favorite",
        ),
    ]
