# Generated by Django 4.1.5 on 2023-10-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_product_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="long_name",
            field=models.CharField(
                blank=True,
                help_text="Введите наименование",
                max_length=255,
                null=True,
                verbose_name="Наименование товара длинное",
            ),
        ),
    ]
