# Generated by Django 4.1.5 on 2023-09-17 12:50

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_event_description_alter_event_name"),
        ("products", "0006_alter_imageset_options_delete_shoppingcart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                help_text="Введите описание", max_length=255, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Введите название", max_length=30, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="imageset",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                help_text="Загрузите изображение",
                upload_to="product_images/",
                verbose_name="Основное изображение",
            ),
        ),
        migrations.AlterField(
            model_name="imageset",
            name="product",
            field=models.ForeignKey(
                help_text="Введите товар",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(
                help_text="Введите производителя", max_length=100, verbose_name="Брэнд"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                help_text="Введите категорию",
                on_delete=django.db.models.deletion.CASCADE,
                to="products.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                help_text="Введите описание", max_length=255, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="event",
            field=models.ForeignKey(
                help_text="Введите промоакцию",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.event",
                verbose_name="Акция",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Введите название", max_length=30, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_per_unit",
            field=models.FloatField(
                default=0,
                help_text="Введите цену за единицу",
                verbose_name="Цена за штуку",
            ),
        ),
        migrations.AlterField(
            model_name="productevent",
            name="event_id",
            field=models.ForeignKey(
                help_text="Введите промоакцию",
                on_delete=django.db.models.deletion.CASCADE,
                to="events.event",
                verbose_name="акция",
            ),
        ),
        migrations.AlterField(
            model_name="productevent",
            name="product_id",
            field=models.ForeignKey(
                help_text="Введите товар",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_event",
                to="products.product",
            ),
        ),
    ]
