# Generated by Django 4.1.5 on 2023-09-17 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_event_description_alter_event_name"),
        ("products", "0007_alter_category_description_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productevent",
            options={
                "verbose_name": "продукт в акции",
                "verbose_name_plural": "продукты а акции",
            },
        ),
        migrations.AlterField(
            model_name="productevent",
            name="event_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="events.event",
                verbose_name="Промоакция",
            ),
        ),
        migrations.AlterField(
            model_name="productevent",
            name="product_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_event",
                to="products.product",
                verbose_name="Товар",
            ),
        ),
    ]
