# Generated by Django 4.1.5 on 2023-09-17 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_alter_productevent_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productevent",
            name="product_id",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_event",
                to="products.product",
                verbose_name="Товар",
            ),
        ),
    ]
