# Generated by Django 4.1.5 on 2023-09-17 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_event_description_alter_event_name"),
        ("products", "0009_alter_productevent_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="Введите промоакцию",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.event",
                verbose_name="Акция",
            ),
        ),
    ]
