# Generated by Django 4.1.5 on 2023-09-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_alter_product_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price_per_unit",
            field=models.FloatField(
                help_text="Введите цену за единицу", verbose_name="Цена за штуку"
            ),
        ),
    ]
