# Generated by Django 4.1.5 on 2023-09-17 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_alter_product_discount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productevent",
            options={
                "verbose_name": "продукт в акции",
                "verbose_name_plural": "продукты в акциях",
            },
        ),
        migrations.AlterField(
            model_name="productevent",
            name="product_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_event",
                to="products.product",
                verbose_name="Товар",
            ),
        ),
    ]
