# Generated by Django 4.1.5 on 2023-09-18 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0014_alter_product_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                help_text="Введите категорию",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="products.category",
                verbose_name="Категория",
            ),
        ),
    ]
