# Generated by Django 4.1.5 on 2023-09-26 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0017_alter_product_discount"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductEvent",
        ),
    ]
